package za.co.pocketot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ExerciseAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExerciseAllPropertiesEquals(Exercise expected, Exercise actual) {
        assertExerciseAutoGeneratedPropertiesEquals(expected, actual);
        assertExerciseAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExerciseAllUpdatablePropertiesEquals(Exercise expected, Exercise actual) {
        assertExerciseUpdatableFieldsEquals(expected, actual);
        assertExerciseUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExerciseAutoGeneratedPropertiesEquals(Exercise expected, Exercise actual) {
        assertThat(actual)
            .as("Verify Exercise auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExerciseUpdatableFieldsEquals(Exercise expected, Exercise actual) {
        assertThat(actual)
            .as("Verify Exercise relevant properties")
            .satisfies(a -> assertThat(a.getUuid()).as("check uuid").isEqualTo(expected.getUuid()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getVideoLink()).as("check videoLink").isEqualTo(expected.getVideoLink()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertExerciseUpdatableRelationshipsEquals(Exercise expected, Exercise actual) {
        // empty method
    }
}
