package za.co.pocketot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrganizationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationAllPropertiesEquals(Organization expected, Organization actual) {
        assertOrganizationAutoGeneratedPropertiesEquals(expected, actual);
        assertOrganizationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationAllUpdatablePropertiesEquals(Organization expected, Organization actual) {
        assertOrganizationUpdatableFieldsEquals(expected, actual);
        assertOrganizationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationAutoGeneratedPropertiesEquals(Organization expected, Organization actual) {
        assertThat(actual)
            .as("Verify Organization auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationUpdatableFieldsEquals(Organization expected, Organization actual) {
        assertThat(actual)
            .as("Verify Organization relevant properties")
            .satisfies(a -> assertThat(a.getUuid()).as("check uuid").isEqualTo(expected.getUuid()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getRegistrationNumber()).as("check registrationNumber").isEqualTo(expected.getRegistrationNumber())
            )
            .satisfies(a -> assertThat(a.getVerified()).as("check verified").isEqualTo(expected.getVerified()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizationUpdatableRelationshipsEquals(Organization expected, Organization actual) {
        // empty method
    }
}
