package za.co.pocketot.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PractitionerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPractitionerAllPropertiesEquals(Practitioner expected, Practitioner actual) {
        assertPractitionerAutoGeneratedPropertiesEquals(expected, actual);
        assertPractitionerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPractitionerAllUpdatablePropertiesEquals(Practitioner expected, Practitioner actual) {
        assertPractitionerUpdatableFieldsEquals(expected, actual);
        assertPractitionerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPractitionerAutoGeneratedPropertiesEquals(Practitioner expected, Practitioner actual) {
        assertThat(actual)
            .as("Verify Practitioner auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPractitionerUpdatableFieldsEquals(Practitioner expected, Practitioner actual) {
        assertThat(actual)
            .as("Verify Practitioner relevant properties")
            .satisfies(a -> assertThat(a.getUuid()).as("check uuid").isEqualTo(expected.getUuid()))
            .satisfies(a -> assertThat(a.getIdDocument()).as("check idDocument").isEqualTo(expected.getIdDocument()))
            .satisfies(a -> assertThat(a.getIdNumber()).as("check idNumber").isEqualTo(expected.getIdNumber()))
            .satisfies(a -> assertThat(a.getDateOfBirth()).as("check dateOfBirth").isEqualTo(expected.getDateOfBirth()))
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getRegistrationNumber()).as("check registrationNumber").isEqualTo(expected.getRegistrationNumber())
            )
            .satisfies(a -> assertThat(a.getVerified()).as("check verified").isEqualTo(expected.getVerified()))
            .satisfies(a -> assertThat(a.getPractitionerType()).as("check practitionerType").isEqualTo(expected.getPractitionerType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPractitionerUpdatableRelationshipsEquals(Practitioner expected, Practitioner actual) {
        assertThat(actual)
            .as("Verify Practitioner relationships")
            .satisfies(a -> assertThat(a.getOrganization()).as("check organization").isEqualTo(expected.getOrganization()));
    }
}
